# Generated by Django 4.2 on 2024-11-27 20:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Del_Instrumento', models.CharField(max_length=100, unique=True, validators=[api.models.validate_only_letters_and_spaces])),
                ('Familia_Del_Instrumento', models.CharField(max_length=50)),
                ('Foto', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
